services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Smichaelsen\FluidViewHelperTimespan\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
    public: true
